apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role_deploy_view
rules:
- apiGroups: ["*"]
  resources: ["pods", "deployments"]
  verbs: ["get", "list", "watch"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: binding_deploy_view
subjects:
- kind: User
  name: deploy_view
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: role_deploy_view
  apiGroup: rbac.authorization.k8s.io