apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-namespace-admin
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: role_sa-namespace-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: binding_sa-namespace-admin
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-namespace-admin
  namespace: default
roleRef:
  kind: Role
  name: role_sa-namespace-admin
  apiGroup: rbac.authorization.k8s.io