apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prod
  name: role_prod_view
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: binding_prod_view
  namespace: prod
subjects:
- kind: User
  name: prod_view
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role_prod_view
  apiGroup: rbac.authorization.k8s.io