apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prod
  name: role_prod_admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: binding_prod_admin
  namespace: prod
subjects:
- kind: User
  name: prod_admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role_prod_admin
  apiGroup: rbac.authorization.k8s.io